version: "3.3"
services:
  advert_portal:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_URL: db
    depends_on:
      - db
############################
  db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/ola/mysql:/var/lib/mysql
