--ADVERTS
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 1', 'Krótki opis 1', 'Długi opis ogłoszenia testowego 1', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'emawal'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'CHEMISTRY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 2', 'Krótki opis 2', 'Długi opis ogłoszenia testowego 2', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'herkwi'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'CHEMISTRY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 3', 'Krótki opis 3', 'Długi opis ogłoszenia testowego 3', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'barkal'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ADMINISTRATION'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 4', 'Krótki opis 4', 'Długi opis ogłoszenia testowego 4', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'brusaw'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ADMINISTRATION'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 5', 'Krótki opis 5', 'Długi opis ogłoszenia testowego 5', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'dormaz'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ARCHITECTURE'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 6', 'Krótki opis 6', 'Długi opis ogłoszenia testowego 6', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'kambrze'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ARCHITECTURE'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 7', 'Krótki opis 7', 'Długi opis ogłoszenia testowego 7', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'kambrze'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'BIOLOGY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 8', 'Krótki opis 8', 'Długi opis ogłoszenia testowego 8', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'dobwys'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'BIOLOGY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 9', 'Krótki opis 9', 'Długi opis ogłoszenia testowego 9', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'dobwys'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'COMPUTER_SCIENCE'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 10', 'Krótki opis 10', 'Długi opis ogłoszenia testowego 10', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'krzzal'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'COMPUTER_SCIENCE'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 11', 'Krótki opis 11', 'Długi opis ogłoszenia testowego 11', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'krzzal'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ELECTRONICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 12', 'Krótki opis 12', 'Długi opis ogłoszenia testowego 12', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'krzzal'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ELECTRONICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 13', 'Krótki opis 13', 'Długi opis ogłoszenia testowego 13', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'jozjak'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'JOURNALISM'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 14', 'Krótki opis 14', 'Długi opis ogłoszenia testowego 14', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'julpie'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'JOURNALISM'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 15', 'Krótki opis 15', 'Długi opis ogłoszenia testowego 15', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'julpie'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MANAGEMENT'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 16', 'Krótki opis 16', 'Długi opis ogłoszenia testowego 16', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'julkal'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MANAGEMENT'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 17', 'Krótki opis 17', 'Długi opis ogłoszenia testowego 17', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'konjas'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MATHEMATICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 18', 'Krótki opis 18', 'Długi opis ogłoszenia testowego 18', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'marsik'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MATHEMATICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 19', 'Krótki opis 19', 'Długi opis ogłoszenia testowego 19', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'marsik'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'OTHER'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 20', 'Krótki opis 20', 'Długi opis ogłoszenia testowego 20', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'agalis'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'OTHER'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 21', 'Krótki opis 21', 'Długi opis ogłoszenia testowego 21', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'natgor'), (SELECT id FROM ADVERT_TYPES WHERE name = 'INDIVIDUAL'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'PHYSICS'), now());

INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 22', 'Krótki opis 22', 'Długi opis ogłoszenia testowego 22', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'matprz'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'PHYSICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 23', 'Krótki opis 23', 'Długi opis ogłoszenia testowego 23', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'matprz'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'PHYSICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 24', 'Krótki opis 24', 'Długi opis ogłoszenia testowego 24', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'felost'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'PHYSICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 25', 'Krótki opis 25', 'Długi opis ogłoszenia testowego 25', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'felost'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'TRANSPORT'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 26', 'Krótki opis 26', 'Długi opis ogłoszenia testowego 26', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'katkub'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'TRANSPORT'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 27', 'Krótki opis 27', 'Długi opis ogłoszenia testowego 27', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'katkub'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'TRANSPORT'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 28', 'Krótki opis 28', 'Długi opis ogłoszenia testowego 28', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'berkwi'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ADMINISTRATION'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 29', 'Krótki opis 29', 'Długi opis ogłoszenia testowego 29', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'berkwi'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ARCHITECTURE'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 30', 'Krótki opis 30', 'Długi opis ogłoszenia testowego 30', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'berkwi'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'BIOLOGY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 31', 'Krótki opis 31', 'Długi opis ogłoszenia testowego 31', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'jadpio'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'BIOLOGY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 32', 'Krótki opis 32', 'Długi opis ogłoszenia testowego 32', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'jadpio'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'CHEMISTRY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 33', 'Krótki opis 33', 'Długi opis ogłoszenia testowego 33', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'monzal'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'CHEMISTRY'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 34', 'Krótki opis 34', 'Długi opis ogłoszenia testowego 34', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'jolkuc'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'COMPUTER_SCIENCE'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 35', 'Krótki opis 35', 'Długi opis ogłoszenia testowego 35', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'magkam'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'COMPUTER_SCIENCE'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 36', 'Krótki opis 36', 'Długi opis ogłoszenia testowego 36', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'klamac'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ELECTRONICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 37', 'Krótki opis 37', 'Długi opis ogłoszenia testowego 37', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'rafmac'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'ELECTRONICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 38', 'Krótki opis 38', 'Długi opis ogłoszenia testowego 38', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'rafmac'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'JOURNALISM'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 39', 'Krótki opis 39', 'Długi opis ogłoszenia testowego 39', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'rafmac'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'JOURNALISM'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 40', 'Krótki opis 40', 'Długi opis ogłoszenia testowego 40', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'arksob'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MANAGEMENT'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 41', 'Krótki opis 41', 'Długi opis ogłoszenia testowego 41', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'arksob'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MANAGEMENT'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 42', 'Krótki opis 42', 'Długi opis ogłoszenia testowego 42', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'remjaw'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MATHEMATICS'), now());
INSERT INTO ADVERTS (title, short_description, long_description, archived, user_id, type_id, category_id, created_at) VALUES ('Ogłoszenie testowe 43', 'Krótki opis 43', 'Długi opis ogłoszenia testowego 43', 0,
                                                                                                                              (SELECT id FROM USERS WHERE login = 'remjaw'), (SELECT id FROM ADVERT_TYPES WHERE name = 'COMPANY'),
                                                                                                                              (SELECT id FROM ADVERT_CATEGORIES WHERE name = 'MATHEMATICS'), now());


