--liquibase formatted sql
--changeset aokrutny:220820211656

INSERT INTO ROLES (name) VALUES ('COMPANY_ADMIN');

INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'COMPANY_ADMIN'), (SELECT id FROM PERMISSIONS WHERE name = 'USER_READ'));
INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'COMPANY_ADMIN'), (SELECT id FROM PERMISSIONS WHERE name = 'COMPANY_READ'));
INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'COMPANY_ADMIN'), (SELECT id FROM PERMISSIONS WHERE name = 'COMPANY_WRITE'));