--liquibase formatted sql
--changeset aokrutny:141120211206

ALTER TABLE FILES ADD COLUMN content_type VARCHAR(100);
ALTER TABLE FILES ADD COLUMN resource_id INTEGER;
ALTER TABLE FILES ADD COLUMN resource_type ENUM ('USER', 'ADVERT', 'COMPANY');
ALTER TABLE FILES ADD COLUMN file_type ENUM ('IMAGE', 'ATTACHMENT');

ALTER TABLE FILES RENAME COLUMN path to s3_key;
