--liquibase formatted sql
--changeset aokrutny:290720211919

CREATE TABLE ROLES (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE PERMISSIONS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE ROLE_PERMISSION (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    role_id INTEGER,
    permission_id INTEGER,
    FOREIGN KEY (role_id) REFERENCES ROLES(id),
    FOREIGN KEY (permission_id) REFERENCES PERMISSIONS(id)
);

CREATE TABLE USER_ROLE (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    role_id INTEGER,
    user_id INTEGER,
    FOREIGN KEY (role_id) REFERENCES ROLES(id),
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);

INSERT INTO ROLES (name) VALUES ('COMPANY_USER');
INSERT INTO ROLES (name) VALUES ('INDIVIDUAL_USER');

INSERT INTO PERMISSIONS (name) VALUES ('USER_READ');
INSERT INTO PERMISSIONS (name) VALUES ('USER_WRITE');
INSERT INTO PERMISSIONS (name) VALUES ('COMPANY_READ');
INSERT INTO PERMISSIONS (name) VALUES ('COMPANY_WRITE');


INSERT INTO ROLE_PERMISSION (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'INDIVIDUAL_USER'), (SELECT id FROM PERMISSIONS WHERE name = 'USER_READ'));
INSERT INTO ROLE_PERMISSION (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'INDIVIDUAL_USER'), (SELECT id FROM PERMISSIONS WHERE name = 'USER_WRITE'));
INSERT INTO ROLE_PERMISSION (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'INDIVIDUAL_USER'), (SELECT id FROM PERMISSIONS WHERE name = 'COMPANY_READ'));

INSERT INTO ROLE_PERMISSION (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'COMPANY_USER'), (SELECT id FROM PERMISSIONS WHERE name = 'USER_READ'));
INSERT INTO ROLE_PERMISSION (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'COMPANY_USER'), (SELECT id FROM PERMISSIONS WHERE name = 'COMPANY_READ'));
INSERT INTO ROLE_PERMISSION (role_id, permission_id) VALUES ((SELECT id FROM ROLES WHERE name = 'COMPANY_USER'), (SELECT id FROM PERMISSIONS WHERE name = 'COMPANY_WRITE'));