--liquibase formatted sql
--changeset aokrutny:111020212020
CREATE TABLE TAGS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE RESOURCE_TAGS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    tag_id INTEGER,
    resource_id INTEGER
);

ALTER TABLE RESOURCE_TAGS ADD CONSTRAINT f_tag_id FOREIGN KEY (tag_id) REFERENCES TAGS(id);
ALTER TABLE RESOURCE_TAGS ADD INDEX (resource_id);
ALTER TABLE RESOURCE_TAGS ADD INDEX (tag_id);