--liquibase formatted sql
--changeset aokrutny:120920211438
ALTER TABLE ADVERTS ADD COLUMN type_id INTEGER;
ALTER TABLE ADVERTS ADD COLUMN category_id INTEGER;
ALTER TABLE ADVERTS ADD COLUMN created_at TIMESTAMP;

ALTER TABLE ADVERTS ADD CONSTRAINT f_type_id FOREIGN KEY (type_id) REFERENCES ADVERT_TYPES(id);
ALTER TABLE ADVERTS ADD CONSTRAINT f_category_id FOREIGN KEY (category_id) REFERENCES ADVERT_CATEGORIES(id);